wheel_model:
  description: 'Wheel model'
  choices: ['nadia', 'moog']
  default_value: 'moog'
arm_type:
  description: 'Arm type'
  choices: ['tiago-arm', 'no-arm']
  default_value: 'tiago-arm'
arm_motor_model:
  description: 'Arm motor model'
  choices: ['parker', 'ilm']
  default_value: 'parker'
laser_model:
  description: 'Base laser model'
  choices: ['no-laser', 'sick-571', 'sick-561', 'sick-551', 'hokuyo']
  default_value: 'sick-571'
wrist_model:
  description: 'Wrist model'
  choices: ['wrist-2010', 'wrist-2017']
  default_value: 'wrist-2017'
end_effector:
  description: 'End effector model'
  choices: ['pal-gripper', 'pal-hey5', 'custom', 'no-end-effector', 'robotiq-2f-85','robotiq-2f-140']
  default_value: 'pal-gripper'
ft_sensor:
  description: 'FT sensor model'
  choices: ['schunk-ft', 'no-ft-sensor']
  default_value: 'schunk-ft'
has_screen:
  description: 'Has screen at torso'
  choices: ['False', 'True']
  default_value: 'False'
base_type:
  description: 'Base type'
  choices: ['pmb2', 'omni_base']
  default_value: 'pmb2'
camera_model:
  description: 'Head camera model'
  choices: ['orbbec-astra', 'orbbec-astra-pro', 'asus-xtion', 'no-camera']
  default_value: 'orbbec-astra'
