/joystick_relay:
  ros__parameters:
    priority: False
    turbo:
      linear_forward_min  : 0.10
      linear_forward_max  : 1.00
      linear_backward_min : 0.10
      linear_backward_max : 1.00
      linear_lateral_min  : 0.10
      linear_lateral_max  : 0.60
      angular_min : 0.1745  # !degrees  10.0 (not supported)
      angular_max : 2.0944  # !degrees 120.0 (not supported)
      steps       : 8