/**:
  ros__parameters:
    motions:
      unfold_arm:
        joints: [torso_lift_joint, arm_1_joint,
        arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
        arm_6_joint, arm_7_joint]
        positions: [0.30, 0.21, 0.35, -0.2, 0.8, -1.57, 1.37, 0.0,
                    0.30, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
        times_from_start: [0.5, 6.0]
        meta:
          name: Unfold arm
          usage: demo
          description: 'unfold_arm'

      reach_floor:
        joints: [torso_lift_joint, arm_1_joint,
        arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
        arm_6_joint, arm_7_joint]
        positions: [0.19, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0,
                    0.19, 1.6, -0.55, -1.35, 1.40, -1.57, -0.07, 0.0,
                    0.16, 1.6, -0.55, 0.0, 1.03, -1.57, -0.07, 0.0]
        times_from_start: [1.0, 3.0, 7.0]
        meta:
          name: Reach Floor
          usage: demo
          description: 'Reach floor'

      reach_max:
        joints: [torso_lift_joint, arm_1_joint,
        arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
        arm_6_joint, arm_7_joint]
        positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0,
                    0.35, 0.9, 0.68, -3.16, 1.10, 2.05, 1.0, 0.0,
                    0.35, 0.9, 1.0, -3.45, 0.45, 2.05, 1.0, 0.0]
        times_from_start: [1.0, 4.0, 7.0]
        meta:
          name: Reach Max
          usage: demo
          description: 'Reach max'

      prepare_grasp:
        joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
        positions: [0.34, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0,
                    0.34, 0.10, 0.47, -0.20, 1.56, -1.58, 0.25, 0.0,
                    0.34, 0.10, 0.47, -0.20, 1.56, 1.60, 0.25, 1.19]
        times_from_start: [3.0, 8.5, 10.5]
        meta:
          name: Prepare Grasp
          usage: demo
          description: 'Prepare grasp position'

      wave:
        joints: [arm_1_joint,
        arm_2_joint, arm_3_joint, arm_4_joint,
        arm_5_joint, arm_6_joint, arm_7_joint]
        positions: [0.09, -0.679638896132783, -3.1087325315620733, 2.0882339360702575, -1.1201172410014792, -0.031008601325809293, -2.0,
                    0.09, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0,
                    0.09, -0.7231278283145929, -2.9385504456273295, 2.18, -1.1201355028397157, -0.031008601325809293, -2.04,
                    0.09, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0]
        times_from_start: [0.0, 1.0, 2.0, 3.0]
        meta:
          name: Wave
          usage: demo
          description: 'wave'

      pregrasp_weight:
        joints: [torso_lift_joint, arm_1_joint,
        arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
        arm_6_joint, arm_7_joint]
        positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        times_from_start: [1.0]
        meta:
          name: Pregrasp Weight
          usage: demo
          description: 'Pregrasp weight'

      do_weights:
        joints: [arm_1_joint,
        arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
        arm_6_joint, arm_7_joint]
        positions: [1.6, -1.48, -3.16, 1.62, -1.57, -0.2, 0.0,
                    1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0,
                    1.6, -1.48, -3.16, 1.62, -1.57, -0.2, 0.0,
                    1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0,
                    1.6, -1.48, -3.16, 1.62, -1.57, -0.2, 0.0,
                    1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0,
                    1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        times_from_start: [1.0, 2.0, 4.0, 6.0, 8.0, 10.0, 12.0]
        meta:
          name: Do Weights
          usage: demo
          description: 'Do weights'

      home:
        joints: [torso_lift_joint, arm_1_joint,
        arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
        arm_6_joint, arm_7_joint]
        positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, -1.58,
                    0.18, 0.50, -1.34, -0.48, 1.94, -1.49, 1.37, -1.58,
                    0.15, 0.50, -1.34, -0.48, 1.94, -1.49, 1.37, 0.0]
        times_from_start: [0.5, 4.0, 7.0]
        meta:
          name: Home
          usage: demo
          description: 'Go home'

      offer:
        joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
        positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577]
        times_from_start: [0.0]
        meta:
          name: Offer Gripper
          usage: demo
          description: 'Offer Gripper'

      shake_hands:
        joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
        positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577,
                    0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577,
                    0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577,
                    0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577,
                    0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577,
                    0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577,
                    0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        times_from_start: [0.0, 5.0, 6.0, 7.0, 8.0, 9.0, 11.0]
        meta:
          name: Shake Hands
          usage: demo
          description: 'shake_hands'

      set_arm3_90:
        joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
        positions: [0.0, 0.0, 1.5708, 0.0, 0.0, 0.0, 0.0]
        times_from_start: [2.0]
        meta:
          name: Set Arm3 to 90 degrees
          usage: demo
          description: 'Set arm_3_joint to 90 degrees (1.5708 rad)'