/**:
  ros__parameters:
    motions:
      inspect_surroundings:
        joints: ['head_1_joint', 'head_2_joint']
        positions: [-1., -0.85,
                    -1., -0.85,
                    1., -0.85,
                    1., -0.85,
                    0., -0.85]
        times_from_start: [1.5, 2.0, 4.5, 5.0, 7.0]
        meta:
          name: Inspect Surroundings
          usage: demo
          description: 'Inspect surroundings around the robot'

      head_tour:
        joints: [head_1_joint, head_2_joint]
        positions: [0.0, 0.0,
                    0.7, 0.4,
                    0.7,-0.4,
                   -0.7,-0.4,
                   -0.7, 0.4,
                    0.0, 0.0]
        times_from_start: [0.1, 3.0, 6.0, 9.0, 12.0, 15.0]
        meta:
          name: Head Tour
          usage: demo
          description: 'head_tour'

      head_nod:
        joints: [head_1_joint, head_2_joint]
        times_from_start: [0.1, 0.8, 1.6]
        positions: [0.0, 0.0,
                    0.0, -0.4,
                    0.0, 0.0]
        meta:
          name: Head Nod
          usage: demo
          description: head_nod

      head_down:
        joints: [head_1_joint, head_2_joint]
        times_from_start: [0.1, 0.8]
        positions: [0.0, 0.0,
                    0.0, -0.4]
        meta:
          name: Head Down
          usage: demo
          description: head_down

      head_front:
        joints: [head_1_joint, head_2_joint]
        times_from_start: [0.8]
        positions: [0.0, 0.0]
        meta:
          name: Head Front
          usage: demo
          description: head_front

      head_shake:
        joints: [head_1_joint, head_2_joint]
        times_from_start: [0.1, 0.8, 1.5, 2.2, 2.9, 3.6, 4.3]
        positions: [0.0, 0.0,
                   -0.4, 0.0,
                    0.0, 0.0,
                    0.4, 0.0,
                    0.0, 0.0,
                   -0.4, 0.0,
                    0.0, 0.0]
        meta:
          name: Head Shake
          usage: demo
          description: head_shake
